### ISSUE TITLE
Selfbot's receiving messages [websocket] no longer works

### ISSUE THREAD

**Issue by TKperson** [Supergamer5465/discord-server-nuke#4]
Starting from April 30, 2021, discord's new update seemed to have broke something in the websocket section according to this page https://stackoverflow.com/questions/67339174/discord-api-soft-ban-for-selfbot-it-can-only-read-its-own-messages.

The thing that was broken: the selfbots will no longer have the ability to receive messages from any channels. Since selfbots are no longer supported by discord, they will not fix this issue.
There is one work around that came to my mind. Which is to fetch the chat messages manually with http requests. But that's going to delay the command execution time (very laggy and ram inefficient)and it's very unreliable because everything are going to be not synchronized.

**Comment by Supergamer5465** [comment]
ok this is deprecated though
